<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="21" passed="18" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-11T11:02:42Z" name=" ActiTime Suite" finished-at="2022-03-11T11:02:43Z" duration-ms="242">
    <groups>
      <group name="Sanity">
        <method signature="TestClassusingTestNG.test1()[pri:0, instance:com.vallabh.TestClassusingTestNG@4c60d6e9]" name="test1" class="com.vallabh.TestClassusingTestNG"/>
        <method signature="TestClassusingTestNG.test5()[pri:0, instance:com.vallabh.TestClassusingTestNG@4c60d6e9]" name="test5" class="com.vallabh.TestClassusingTestNG"/>
        <method signature="TestClassusingTestNG.test6()[pri:0, instance:com.vallabh.TestClassusingTestNG@4c60d6e9]" name="test6" class="com.vallabh.TestClassusingTestNG"/>
        <method signature="TestClassusingTestNG.test1()[pri:0, instance:com.vallabh.TestClassusingTestNG@6440112d]" name="test1" class="com.vallabh.TestClassusingTestNG"/>
        <method signature="TestClassusingTestNG.test5()[pri:0, instance:com.vallabh.TestClassusingTestNG@6440112d]" name="test5" class="com.vallabh.TestClassusingTestNG"/>
        <method signature="TestClassusingTestNG.test6()[pri:0, instance:com.vallabh.TestClassusingTestNG@6440112d]" name="test6" class="com.vallabh.TestClassusingTestNG"/>
        <method signature="TestClassusingTestNG.test1()[pri:0, instance:com.vallabh.TestClassusingTestNG@451001e5]" name="test1" class="com.vallabh.TestClassusingTestNG"/>
        <method signature="TestClassusingTestNG.test5()[pri:0, instance:com.vallabh.TestClassusingTestNG@451001e5]" name="test5" class="com.vallabh.TestClassusingTestNG"/>
        <method signature="TestClassusingTestNG.test6()[pri:0, instance:com.vallabh.TestClassusingTestNG@451001e5]" name="test6" class="com.vallabh.TestClassusingTestNG"/>
      </group> <!-- Sanity -->
      <group name="Smoke">
        <method signature="TestClassusingTestNG.test2()[pri:0, instance:com.vallabh.TestClassusingTestNG@4c60d6e9]" name="test2" class="com.vallabh.TestClassusingTestNG"/>
        <method signature="TestClassusingTestNG.test4()[pri:0, instance:com.vallabh.TestClassusingTestNG@4c60d6e9]" name="test4" class="com.vallabh.TestClassusingTestNG"/>
        <method signature="TestClassusingTestNG.test2()[pri:0, instance:com.vallabh.TestClassusingTestNG@6440112d]" name="test2" class="com.vallabh.TestClassusingTestNG"/>
        <method signature="TestClassusingTestNG.test4()[pri:0, instance:com.vallabh.TestClassusingTestNG@6440112d]" name="test4" class="com.vallabh.TestClassusingTestNG"/>
        <method signature="TestClassusingTestNG.test2()[pri:0, instance:com.vallabh.TestClassusingTestNG@451001e5]" name="test2" class="com.vallabh.TestClassusingTestNG"/>
        <method signature="TestClassusingTestNG.test4()[pri:0, instance:com.vallabh.TestClassusingTestNG@451001e5]" name="test4" class="com.vallabh.TestClassusingTestNG"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2022-03-11T11:02:42Z" name="Test1" finished-at="2022-03-11T11:02:42Z" duration-ms="73">
      <class name="com.vallabh.TestClassusingTestNG">
        <test-method signature="test1()[pri:0, instance:com.vallabh.TestClassusingTestNG@4c60d6e9]" started-at="2022-03-11T11:02:42Z" name="test1" finished-at="2022-03-11T11:02:42Z" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test2()[pri:0, instance:com.vallabh.TestClassusingTestNG@4c60d6e9]" started-at="2022-03-11T11:02:42Z" name="test2" finished-at="2022-03-11T11:02:42Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method signature="test2()[pri:0, instance:com.vallabh.TestClassusingTestNG@4c60d6e9]" started-at="2022-03-11T11:02:42Z" name="test2" finished-at="2022-03-11T11:02:42Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method signature="test2()[pri:0, instance:com.vallabh.TestClassusingTestNG@4c60d6e9]" started-at="2022-03-11T11:02:42Z" name="test2" finished-at="2022-03-11T11:02:42Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method signature="test4()[pri:0, instance:com.vallabh.TestClassusingTestNG@4c60d6e9]" started-at="2022-03-11T11:02:42Z" name="test4" finished-at="2022-03-11T11:02:42Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method signature="test5()[pri:0, instance:com.vallabh.TestClassusingTestNG@4c60d6e9]" started-at="2022-03-11T11:02:42Z" name="test5" finished-at="2022-03-11T11:02:42Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
        <test-method signature="test6()[pri:0, instance:com.vallabh.TestClassusingTestNG@4c60d6e9]" started-at="2022-03-11T11:02:42Z" name="test6" description="test 6 fails..using assertions" finished-at="2022-03-11T11:02:42Z" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.vallabh.TestClassusingTestNG.test6(TestClassusingTestNG.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6 -->
      </class> <!-- com.vallabh.TestClassusingTestNG -->
    </test> <!-- Test1 -->
    <test started-at="2022-03-11T11:02:43Z" name="Test2" finished-at="2022-03-11T11:02:43Z" duration-ms="23">
      <class name="com.vallabh.TestClassusingTestNG">
        <test-method is-config="true" signature="test1(java.lang.String)[pri:0, instance:com.vallabh.TestClassusingTestNG@6440112d]" started-at="2022-03-11T11:02:43Z" name="test1" finished-at="2022-03-11T11:02:43Z" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test1()[pri:0, instance:com.vallabh.TestClassusingTestNG@6440112d]" started-at="2022-03-11T11:02:43Z" name="test1" finished-at="2022-03-11T11:02:43Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test2()[pri:0, instance:com.vallabh.TestClassusingTestNG@6440112d]" started-at="2022-03-11T11:02:43Z" name="test2" finished-at="2022-03-11T11:02:43Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method signature="test2()[pri:0, instance:com.vallabh.TestClassusingTestNG@6440112d]" started-at="2022-03-11T11:02:43Z" name="test2" finished-at="2022-03-11T11:02:43Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method signature="test2()[pri:0, instance:com.vallabh.TestClassusingTestNG@6440112d]" started-at="2022-03-11T11:02:43Z" name="test2" finished-at="2022-03-11T11:02:43Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method signature="test4()[pri:0, instance:com.vallabh.TestClassusingTestNG@6440112d]" started-at="2022-03-11T11:02:43Z" name="test4" finished-at="2022-03-11T11:02:43Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method signature="test5()[pri:0, instance:com.vallabh.TestClassusingTestNG@6440112d]" started-at="2022-03-11T11:02:43Z" name="test5" finished-at="2022-03-11T11:02:43Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
        <test-method signature="test6()[pri:0, instance:com.vallabh.TestClassusingTestNG@6440112d]" started-at="2022-03-11T11:02:43Z" name="test6" description="test 6 fails..using assertions" finished-at="2022-03-11T11:02:43Z" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.vallabh.TestClassusingTestNG.test6(TestClassusingTestNG.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6 -->
      </class> <!-- com.vallabh.TestClassusingTestNG -->
    </test> <!-- Test2 -->
    <test started-at="2022-03-11T11:02:43Z" name="Test3" finished-at="2022-03-11T11:02:43Z" duration-ms="38">
      <class name="com.vallabh.TestClassusingTestNG">
        <test-method is-config="true" signature="test1(java.lang.String)[pri:0, instance:com.vallabh.TestClassusingTestNG@451001e5]" started-at="2022-03-11T11:02:43Z" name="test1" finished-at="2022-03-11T11:02:43Z" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[IE]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test1()[pri:0, instance:com.vallabh.TestClassusingTestNG@451001e5]" started-at="2022-03-11T11:02:43Z" name="test1" finished-at="2022-03-11T11:02:43Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test2()[pri:0, instance:com.vallabh.TestClassusingTestNG@451001e5]" started-at="2022-03-11T11:02:43Z" name="test2" finished-at="2022-03-11T11:02:43Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method signature="test2()[pri:0, instance:com.vallabh.TestClassusingTestNG@451001e5]" started-at="2022-03-11T11:02:43Z" name="test2" finished-at="2022-03-11T11:02:43Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method signature="test2()[pri:0, instance:com.vallabh.TestClassusingTestNG@451001e5]" started-at="2022-03-11T11:02:43Z" name="test2" finished-at="2022-03-11T11:02:43Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method signature="test4()[pri:0, instance:com.vallabh.TestClassusingTestNG@451001e5]" started-at="2022-03-11T11:02:43Z" name="test4" finished-at="2022-03-11T11:02:43Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method signature="test5()[pri:0, instance:com.vallabh.TestClassusingTestNG@451001e5]" started-at="2022-03-11T11:02:43Z" name="test5" finished-at="2022-03-11T11:02:43Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
        <test-method signature="test6()[pri:0, instance:com.vallabh.TestClassusingTestNG@451001e5]" started-at="2022-03-11T11:02:43Z" name="test6" description="test 6 fails..using assertions" finished-at="2022-03-11T11:02:43Z" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.vallabh.TestClassusingTestNG.test6(TestClassusingTestNG.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6 -->
      </class> <!-- com.vallabh.TestClassusingTestNG -->
    </test> <!-- Test3 -->
  </suite> <!--  ActiTime Suite -->
</testng-results>
